service: aws-lambda

frameworkVersion: "2"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: optimize.handle
    environment:
      bucket: serverless
    eventS:
      - s3:
          bucket: serverless
          event: s3:ObjectCreated:*
          rules:
            - preffix: uploads/
            - suffix: .jpg
      - s3:
          bucket: serverless
          event: s3:ObjectCreated:*
          rules:
            - preffix: uploads/
            - suffix: .png
