service: aws-lambda

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-plugin-typescript
